name: Build & Test Pipeline

on:
  push:
    branches:
      - master
      - feature-*   # Suveikia visoms šakoms, prasidedančioms "feature-"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

#    - name: Debug – show pytest test discovery
#      run: |
#        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
#        python -m pytest test/ --collect-only -v


    - name: Run tests in 2nd_tests folder (with PYTHONPATH)
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest 2nd_tests/ -v --tb=short --disable-warnings | tee test-output.log
#
    - name: Run pytest tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest test/ -v --tb=short --disable-warnings | tee test-pytest-output.log

    - name: Run unittest tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        python -m unittest discover -s test -p "test_*.py" -v | tee test-unittest-output.log
    
    

    - name: Archive test logs
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: |
         test-output.log
         test-feature-output.log


